/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intarface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.Random;
import javax.swing.ImageIcon;

import javax.swing.JButton;

/**
 *
 * @author EnzoLeite
 */
public class Jogo2 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jogo2.class.getName());

     JButton [][] btnCampos = new JButton[10][10];
     boolean [][] bombas = new boolean[10][10];
     boolean [][] abertos = new boolean[10][10];
     int quantidadedeBombas = 15;
     boolean jogoEncerrado= false;
     int quantidadeCasasAbertas=0;

    public Jogo2() {
        initComponents();
        painelCampo.setPreferredSize(new Dimension(900,700));
        CriarTabuleiro();

    }

      public void CriarTabuleiro(){
        // definir que o painel será divido em 10 linhas e 10 colunas
        // com altura 2px e largura 2px
        painelCampo.setLayout(new GridLayout(10,10,2,2));

        for(int coluna=0;coluna<=9;coluna++){
            for(int linha=0;linha<=9;linha++){
                // váriavel botão para guardar os dados provisorios
                JButton botao = new JButton();
                botao.setFont(new Font("Arial",Font.BOLD,16));// fonte
                botao.setBackground(new Color(255,192,230));// cor de fundo
                botao.setForeground(Color.WHITE);// cor de texto

                // remover marcas do botão que vem por padrão
                botao.setFocusPainted(false);
                botao.setEnabled(false);
                final int linhaSelecionada = linha;
                final int colunaSelecionada = coluna;
                botao.addActionListener((ActionEvent Evento) -> { 
                    abrirbotao(linhaSelecionada,colunaSelecionada);
                    
                });
                
           
                //adicionar o botao dentro da matriz
                btnCampos[linha][coluna]=botao;
                // adicionar ele dentro do painel
                painelCampo.add(botao);

            }// fim do 2° for
        }// fim do 1° for

    }// fim do metodo CriarTabuleiro

      public void AdicionarBombas(){

          Random sorteador = new Random();
          int bombasAdicionadas = 0;



          while(bombasAdicionadas< quantidadedeBombas){
              int linha = sorteador.nextInt(10);
              int coluna = sorteador.nextInt(10);
              if(!bombas[linha][coluna]){
                bombas[linha][coluna]=true;
                bombasAdicionadas++;

          }
          }
      }

       public void iniciarJogo(){
          AdicionarBombas();

          for (int colunas=0;colunas<=9;colunas++){
              for (int linhas=0;linhas<=9;linhas++){
                  JButton botao = btnCampos[linhas][colunas];
                  botao.setEnabled(true);

              }
          }
          btniniciar.setText ("REINICIAR");


       }

       public void abrirbotao(int linha, int coluna){
           if(jogoEncerrado){
              return;
           }
           if(abertos[linha][coluna]){
             return;
           }
           abertos[linha][coluna]=true;
              quantidadeCasasAbertas++;

              JButton botao = btnCampos[linha][coluna];

              if(bombas[linha][coluna]){
                  ImageIcon imgBomba = new ImageIcon( getClass().getResource("Interface/nuclear-explosion.png"));
                  botao.setIcon(imgBomba);
                  return;

              }else{
               ImageIcon imgBandeira = new ImageIcon( getClass().getResource("Interface/red-flag.png"));
               botao.setIcon(imgBandeira);
               return;
              }
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btniniciar = new javax.swing.JButton();
        tftempo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        painelCampo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btniniciar.setBackground(new java.awt.Color(242, 242, 242));
        btniniciar.setText("iniciar");
        btniniciar.addActionListener(this::btniniciarActionPerformed);

        tftempo.setEditable(false);
        tftempo.setText("00:00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Campo minado");

        javax.swing.GroupLayout painelCampoLayout = new javax.swing.GroupLayout(painelCampo);
        painelCampo.setLayout(painelCampoLayout);
        painelCampoLayout.setHorizontalGroup(
            painelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelCampoLayout.setVerticalGroup(
            painelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303)
                .addComponent(tftempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btniniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(painelCampo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btniniciar)
                            .addComponent(tftempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addGap(45, 45, 45)
                .addComponent(painelCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
        // TODO add your handling code here:
        iniciarJogo();
    }//GEN-LAST:event_btniniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jogo2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btniniciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel painelCampo;
    private javax.swing.JTextField tftempo;
    // End of variables declaration//GEN-END:variables
}
